### PR TITLE
Implemented sarch and sbase64 with error handling and comments.

### PR DESCRIPTION
**Pull request by sme272**

### CODE REVIEW

**Review by honestly-nuts — APPROVED** [review]
Note: I dont know how base64 works or what it does so I'm going to assume it is working

**Comment by sme272** [comment]
Quick test encoding and decoding a file worked. I'll get around to adding some proper tests at some point.

**Comment by honestly-nuts** [comment]
You might want to rename a few function because they collide with the real methods of base64.

**Comment by honestly-nuts** [comment]
Quick question, how can I contact you if I want to ask you a few questions about your pull requests. If you are okay with that.

**Comment by honestly-nuts** [comment]
Quick question, how can I contact you if I want to ask you a few questions about your pull requests. If you are okay with that.

**Comment by sme272** [comment]
You on discord? Failing that I'll email you.

**Pull request merged**
